[pytest]
# Indica qual é o módulo de configurações do Django
DJANGO_SETTINGS_MODULE = config.settings

# Informa ao pytest que os códigos Python começam a partir da pasta 'src'
pythonpath = src

# Padrões de arquivos que o pytest deve procurar
python_files = tests.py test_*.py *_tests.py