# pytest.ini
[pytest]
# 1. Informa ao pytest-django onde ficam as configurações do projeto
DJANGO_SETTINGS_MODULE = config.settings

# 2. Configura a pasta 'src' como raiz de busca de módulos do Python
pythonpath = src

# 3. Define o padrão de nomenclatura dos arquivos de teste
python_files = test_*.py

# 4. Resolve o erro de 'import file mismatch' e força o isolamento dos apps
addopts = --import-mode=importlib
