# Generated by Django 5.1.15 on 2026-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("marca", models.CharField(blank=True, max_length=120)),
                ("categoria", models.CharField(blank=True, max_length=120)),
                ("codigo_barras", models.CharField(max_length=32, unique=True)),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidade_medida", models.CharField(max_length=20)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
            },
        ),
    ]
