# Generated by Django 5.1.15 on 2026-06-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("marca", models.CharField(blank=True, max_length=120)),
                ("categoria", models.CharField(blank=True, max_length=120)),
                ("codigo_barras", models.CharField(max_length=32)),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidade_medida", models.CharField(max_length=20)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("rejeitada", "Rejeitada"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "produto_criado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_origem",
                        to="catalog.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de produto",
                "verbose_name_plural": "Solicitações de produtos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
