# Generated by Django 5.1.15 on 2026-07-01 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_ajustar_solicitacao_usuario_nome_produto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="solicitacaoproduto",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Solicitação de Produto",
                "verbose_name_plural": "Solicitações de Produtos",
            },
        ),
        migrations.RemoveField(
            model_name="produto",
            name="atualizado_em",
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.CharField(default="Outros", max_length=100),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="marca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="produto",
            name="unidade_medida",
            field=models.CharField(default="un", max_length=20),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="categoria",
            field=models.CharField(default="Outros", max_length=100),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="codigo_barras",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código de Barras"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data de Envio"),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="marca",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="nome_produto",
            field=models.CharField(max_length=255, verbose_name="Nome do Produto"),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente de Análise"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="unidade_medida",
            field=models.CharField(default="un", max_length=20),
        ),
        migrations.AlterField(
            model_name="solicitacaoproduto",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
            preserve_default=False,
        ),
    ]
